// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../main/colorShifters.h"

lv_obj_t *ui_Primary = NULL;
lv_obj_t *ui_Title = NULL;
lv_obj_t *ui_CurrentSpeedLabel = NULL;
lv_obj_t *ui_CurrentSpeed = NULL;
lv_obj_t *ui_ProgramSpeedLabel = NULL;
lv_obj_t *ui_ProgramSpeed = NULL;
lv_obj_t *ui_FrequencyLabel = NULL;
lv_obj_t *ui_Frequency = NULL;
lv_obj_t *ui_Status = NULL;

// event funtions

// build funtions

void ui_Primary_screen_init(void)
{
ui_Primary = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Primary, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Primary, lv_color_hex(0x0a000a), LV_PART_MAIN | LV_STATE_DEFAULT ); //0x252323
lv_obj_set_style_bg_opa(ui_Primary, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title = lv_label_create(ui_Primary);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title, 0 );
lv_obj_set_y( ui_Title, -99 );
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"TechnoCNC Router Control");
lv_obj_set_style_text_color(ui_Title, lv_color_hex(rgb2rbg(0xffff00)), LV_PART_MAIN | LV_STATE_DEFAULT ); // 0xFFC83D
lv_obj_set_style_text_opa(ui_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Title, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurrentSpeedLabel = lv_label_create(ui_Primary);
lv_obj_set_width( ui_CurrentSpeedLabel, 180);
lv_obj_set_height( ui_CurrentSpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CurrentSpeedLabel, 15 );
lv_obj_set_y( ui_CurrentSpeedLabel, 50 );
lv_label_set_text(ui_CurrentSpeedLabel,"Current Speed:");
// lv_obj_set_style_text_color(ui_CurrentSpeedLabel, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_color(ui_CurrentSpeedLabel, lv_color_hex(rgb2rbg(0x00faff)), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurrentSpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CurrentSpeedLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurrentSpeedLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurrentSpeed = lv_label_create(ui_Primary);
lv_obj_set_width( ui_CurrentSpeed, 180);
lv_obj_set_height( ui_CurrentSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CurrentSpeed, 120 );
lv_obj_set_y( ui_CurrentSpeed, 55 );
lv_label_set_text(ui_CurrentSpeed,"0");
lv_obj_set_style_text_color(ui_CurrentSpeed, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurrentSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CurrentSpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurrentSpeed, &lv_font_unscii_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ProgramSpeedLabel = lv_label_create(ui_Primary);
lv_obj_set_width( ui_ProgramSpeedLabel, 180);
lv_obj_set_height( ui_ProgramSpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ProgramSpeedLabel, 15 );
lv_obj_set_y( ui_ProgramSpeedLabel, 90 );
lv_label_set_text(ui_ProgramSpeedLabel,"Program Speed:");
lv_obj_set_style_text_color(ui_ProgramSpeedLabel, lv_color_hex(rgb2rbg(0x00faff)), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ProgramSpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ProgramSpeedLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ProgramSpeedLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ProgramSpeed = lv_label_create(ui_Primary);
lv_obj_set_width( ui_ProgramSpeed, 180);
lv_obj_set_height( ui_ProgramSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ProgramSpeed, 120 );
lv_obj_set_y( ui_ProgramSpeed, 95 );
lv_label_set_text(ui_ProgramSpeed,"24,000");
lv_obj_set_style_text_color(ui_ProgramSpeed, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ProgramSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ProgramSpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ProgramSpeed, &lv_font_unscii_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FrequencyLabel = lv_label_create(ui_Primary);
lv_obj_set_width( ui_FrequencyLabel, 180);
lv_obj_set_height( ui_FrequencyLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FrequencyLabel, 15 );
lv_obj_set_y( ui_FrequencyLabel, 130 );
lv_label_set_text(ui_FrequencyLabel,"Frequency:");
lv_obj_set_style_text_color(ui_FrequencyLabel, lv_color_hex(rgb2rbg(0x00faff)), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FrequencyLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FrequencyLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FrequencyLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Frequency = lv_label_create(ui_Primary);
lv_obj_set_width( ui_Frequency, 180);
lv_obj_set_height( ui_Frequency, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Frequency, 120 );
lv_obj_set_y( ui_Frequency, 135 );
lv_label_set_text(ui_Frequency,"8,000");
lv_obj_set_style_text_color(ui_Frequency, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Frequency, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Frequency, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Frequency, &lv_font_unscii_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status = lv_label_create(ui_Primary);
lv_obj_set_width( ui_Status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Status, -6 );
lv_obj_set_y( ui_Status, -30 );
lv_obj_set_align( ui_Status, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Status,"OFF");
lv_obj_set_style_text_color(ui_Status, lv_color_hex(rgb2rbg(0x00ff00)), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Primary_screen_destroy(void)
{
   if (ui_Primary) lv_obj_del(ui_Primary);

// NULL screen variables
ui_Primary= NULL;
ui_Title= NULL;
ui_CurrentSpeedLabel= NULL;
ui_CurrentSpeed= NULL;
ui_ProgramSpeedLabel= NULL;
ui_ProgramSpeed= NULL;
ui_FrequencyLabel= NULL;
ui_Frequency= NULL;
ui_Status= NULL;

}
