// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef MAIN_UI_SCREENS_UI_PRIMARY
#define MAIN_UI_SCREENS_UI_PRIMARY

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Primary
extern void ui_Primary_screen_init(void);
extern void ui_Primary_screen_destroy(void);
extern lv_obj_t *ui_Primary;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_CurrentSpeedLabel;
extern lv_obj_t *ui_CurrentSpeed;
extern lv_obj_t *ui_ProgramSpeedLabel;
extern lv_obj_t *ui_ProgramSpeed;
extern lv_obj_t *ui_FrequencyLabel;
extern lv_obj_t *ui_Frequency;
extern lv_obj_t *ui_ElapsedLabel;
extern lv_obj_t *ui_Elapsed;
extern lv_obj_t *ui_Status;
extern lv_obj_t *UI_DeltaLabel;
extern lv_obj_t *ui_Delta;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif  /* MAIN_UI_SCREENS_UI_PRIMARY */

