// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_splash = NULL;
// event funtions
void ui_event_splash( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Primary, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Primary_screen_init);
}
}

// build funtions

void ui_splash_screen_init(void)
{
ui_splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_splash, &ui_img_router_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_splash, ui_event_splash, LV_EVENT_ALL, NULL);

}

void ui_splash_screen_destroy(void)
{
   if (ui_splash) lv_obj_del(ui_splash);

// NULL screen variables
ui_splash= NULL;

}
