// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef MAIN_UI_SCREENS_UI_SPLASH
#define MAIN_UI_SCREENS_UI_SPLASH

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_splash
extern void ui_splash_screen_init(void);
extern void ui_splash_screen_destroy(void);
extern void ui_event_splash( lv_event_t * e);
extern lv_obj_t *ui_splash;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif  /* MAIN_UI_SCREENS_UI_SPLASH */

