// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef MAIN_UI_UI
#define MAIN_UI_UI

#ifdef __cplusplus
extern "C" {
#endif


#include "ui_helpers.h"
#include "ui_events.h"
#include <lvgl.h>

///////////////////// SCREENS ////////////////////
#include "screens/ui_splash.h"
#include "screens/ui_Primary.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_router_png);   // assets/router.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif  /* MAIN_UI_UI */
